import Vue from "vue";
import row from "ant-design-vue/lib/row";
import menu from "ant-design-vue/lib/menu";
import breadcrumb from "ant-design-vue/lib/breadcrumb";
import card from "ant-design-vue/lib/card";
import tag from "ant-design-vue/lib/tag";
import backTop from "ant-design-vue/lib/back-top";
import pagination from "ant-design-vue/lib/pagination";
import input from "ant-design-vue/lib/input";
import cascader from "ant-design-vue/lib/cascader";
import button from "ant-design-vue/lib/button";

Vue.use(row);
Vue.use(menu);
Vue.use(breadcrumb);
Vue.use(card);
Vue.use(tag);
Vue.use(backTop);
Vue.use(pagination);
Vue.use(input);
Vue.use(cascader);
Vue.use(button);
